# -*- coding: utf-8 -*-
"""nip7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJ5q0pIIUleyUVKasD9DDIQz4lZcblDI
"""

!python -m spacy download en_core_web_sm

import spacy
nlp=spacy.load("en_core_web_sm")

text = "Aissms is best college"
doc = nlp(text)

for i in doc.ents:
  print(i.text,":",i.label_)

test_texts=[
     ("Google announced a new Pixel phone in California.", ["Google", "Pixel", "California"]),
    ("Elon Musk founded SpaceX and Tesla.", ["Elon Musk", "SpaceX", "Tesla"]),
]

correct=0
total=0
forv text , i in test_texts:
  doc=nlp(text)
  found_entity=[ent.text for ent in doc]