# -*- coding: utf-8 -*-
"""nlp6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oi5zFHZtEUylbCCg6duMY3sfKb_fdRJ9
"""

!pythom -m spacy download en_core_web_sm

import spacy
nlp=spacy('en_core_web_sm')

from sklearn.metrics import classification_report

def pred_entity(text):
  nlp=spacy.load('en_core_web_sm')
  doc=nlp(text)
  return [(ent.text,ent.label_)for ent in doc.ents]

def eval(text_labels):
  t_label=[]
  pred_label=[]
  for text,true_ents in text_labels:
    pred=pred_entity(text)
    t_label.extend([label for (_,label) in true_ents])
    pred_label.extend([label for (_,label) in pred])
  return classification_report(t_label,pred_label )

text = "Apple CEO Tim Cook announced new iPhone models in California yesterday."
print("\nExample Text entities: ")
for entity, label in pred_entity(text):
    print(f"{entity}: {label}")

test_data=[("Microsoft's Satya NAdella visited London.",
            [("microsoft","ORG"),("Satya Nadella","PERSON"),("London","GPE")]),
           ("Google opened a new office in Paris.",
            [("Google","ORG"),("Paris","GRE")])]

print("\nEvaluation Results: ")
print(eval(test_data))

